config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'persons/profile'

  resources :projects, only: [:index, :create, :update, :destroy] do
    resources :tasks, only: [:create, :update, :destroy] do
      collection { post :sort }
    end
  end

   root 'projects#index'

   get 'persons/profile', as: 'user_root'

end

app/models/list.rb
class List < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
    has_many :tasks, -> { order(position: :asc) }, dependent: :destroy
    validates :title, presence: true, length: { minimum: 5, maximum: 35 }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  acts_as_list scope: :project
  validates :title, :date, presence: true, length: { minimum: 1 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @projects = current_user.projects
    @project  = Project.new
  end

  def create
    @project = current_user.projects.new(project_params)
    @projects = current_user.projects
    respond_to do |format|
      if @project.save
        format.js  {}
      else
        format.js  {render nothing: true}
      end
    end
  end

  def update
    @project = current_user.projects.find(params[:id])
    @projects = current_user.projects
    respond_to do |format|
      if @project.update(project_params)
        format.js  {}
      else
        format.js  {render nothing: true}
      end
    end
  end

  def destroy
    @project = current_user.projects.find(params[:id])
    @project.destroy
  end


  private
    def project_params
      params.require(:project).permit(:title)
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    respond_to do |format|
      if @task.save
        format.js  {}
      else
        format.js  {render nothing: true}
      end
    end
  end

  def destroy
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @task.destroy
  end

  def update
    @project = current_user.projects.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    respond_to do |format|
      if @task.update(task_params)
        format.js  {}
      else
        format.js  {render nothing: true}
      end
    end
  end

  def sort
    params[:task].each_with_index do |id, index|
    Task.where(id: id).update_all({position: index+1})
    end
    render nothing: true
  end

  private
    def task_params
      params.require(:task).permit(:title, :date, :position, :done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TODOlist</title>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
 
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@list.errors.count, "error") %> prohibited
        this list from being saved:
      </h2>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
 <% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', lists_path %>

app/views/lists/new.html.erb
<h1>Add TODO list</h1>

<%= form_for :list, url: lists_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/persons/profile.html.erb
<div class="devise_persons_profile">
<h1>Profile</h1>
<p>My Email: <%=current_user.email%></p>
<p><%=link_to 'projects', root_path%></p>
</div>

app/views/projects/_project.html.erb
<div class="project" id="<%= project.id %>">

  <div class="list_title">

    <%= form_for project, remote: true, method: :patch do |f| %>
      <%= f.text_field :title %>
      <%= f.submit 'Update Project', class: "edit_project_button" %>
    <% end %>

    <%= image_tag("note.gif", class: "note_list_img") %>
    <span class="title" id="title<%= project.id %>">
    <%= I18n.t('projects.title', project_name: project.title) %>
    </span>
    <%= link_to image_tag("title_trash.gif", class: "title_trash_list_img"), project_path(project), remote: true, method: :delete %>
    <%= image_tag("title_pen.gif", class: "title_pen_list_img") %>

  </div>

  <div class="list_addtask">

    <%= image_tag("plus.gif", class: "addtask_plus") %>
    <%= form_for [project, Task.new], remote: true do |f| %>
      <%= f.text_field :title, :placeholder => "Start typing here to create a task..." %>
      <%= f.date_field :date %>
      <%= f.submit "Add Task", class: "addtask_button" %>
    <% end %>

  </div>

  <ul class="tasks_ul" update-url-data="<%= sort_project_tasks_path(project.id) %>">
    <%= render project.tasks %>
  </ul>

</div>

app/views/projects/create.js.erb
$("<%= escape_javascript(render @project) %>").appendTo(".projects");
$('.new_project').slideUp(1000);

app/views/projects/destroy.js.erb
//remove project window
$('#<%= @project.id %>').fadeOut(500, function (){
	$(this).remove()
});

app/views/projects/index.html.erb
<div class="main">
  
  <%=link_to 'My profile',  persons_profile_path %>
 
  <% if user_signed_in? %>
      <span><%= current_user.email %></span>
      <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
  <% else %>
      <%= link_to 'Sign In', new_user_session_path %> или <%= link_to 'Sign Up',new_user_registration_path %>
  <% end %>
  

  <h2>SIMPLE TODO LIST</h2>
  <h4>FROM RUBY GARAGE</h4>


  <div class="projects" >
    <%= render @projects %>
  </div>

  <div class="button_block">
    <a href="" class="button">
        <%= image_tag("addlist_button.gif", class: "list_img") %>
        <span class="addlist">Add TODO List</span>
    </a>
  </div>

  <%= form_for @project, remote: true do |f| %>
    <%= f.text_field :title, :placeholder => ' Enter new project here..' %>
    <%= f.submit 'Add Project' %>
  <% end %>

  <div id="pusher"></div>
  <div id="footer"> 
    <footer>&copy; Ruby Garage</footer>
  </div>
  
</div>

app/views/projects/update.js.erb
$("#title<%= @project.id %>").text("<%= @project.title %>");

app/views/tasks/_task.html.erb
<%= content_tag_for :li, task do %>

  <div class="task_checkbox" >
    <%= check_box_tag '', '', task.done, class: 'checkbox' %>
  </div>
          
  <div class="task_name">
    <span class="task_entered_name" id="task_title_<%= task.id %>"><%= I18n.t('tasks.title', task_name: task.title) %></span>
    <span class="task_deadline_name">deadline</span>
    <span class="task_deadline_date" id="date_<%= task.id %>"><%= task.date %></span>
  </div>
          
  <div class="task_img">
    <%= image_tag("list_pen.png", class: "pen_list_img") %>
    <%= image_tag("list_line.png", class: "line_list_img") %>
    <%= link_to image_tag("list_trash.png", class: "trash_list_img"), [task.project, task], remote: true, method: :delete  %>
  </div>

  <%= form_for [task.project, task], remote: true, method: :patch do |f| %>
    <%= f.text_field :title, class: "task_title_update" %>
    <%= f.date_field :date, class: "task_date_update" %>
    <%= f.submit 'Update', class: "edit_task_button" %>
  <% end %>

<% end %>

app/views/tasks/create.js.erb
$("<%= escape_javascript(render @task) %>").appendTo("#<%=@project.id %> .tasks_ul");

app/views/tasks/destroy.js.erb
$("#task_<%=@task.id %>").fadeOut(500, function (){
  $(this).remove()
});

app/views/tasks/update.js.erb
$("#task_title_<%= @task.id %>").text("<%= @task.title %>");
$("#date_<%= @task.id %>").text("<%= @task.date %>");